### ISSUE TITLE
Support for error-handling callback

### ISSUE THREAD

**Issue by a1gemmel** [davidkudera/google-maps-loader#42]
For my use-case of this loader, it would be nice to have support for catching problems with loading the API, like `NoApiKeys` or `InvalidApiKey`.

Something like:
```javascript
GoogleMapsLoader.load((google, errorState) => {
   if (errorState) {
       // graceful degradation
    } else {
        // do thing
    }
});
```
or 
```javascript
GoogleMapsLoader.load(
    (google) => { /* do thing */ }, 
    (err) => { /* graceful degradation */}
);
```

If this is something that other people have interest in, I can look into making a PR.

**Comment by davidkudera** [comment]
Hi and thanks for suggestion, it is definitelly something what we should have.

If you could create PR I'll be most grateful

**Comment by krasimir** [comment]
I'm interested in seeing this but wondering how could be implemented. For sure we can check for a missing key or maybe invalid one if we know how to validate the input but correct me if I'm wrong we can't say when the jsonp request failed. It's just adding a script tag and waiting for our callback execution. The error handling in similar libraries is more or less waiting for calling the callback like 5 seconds and if it doesn't happen we consider the process failing. So, do you guys know any good approach for checking if the loader failed.

**Comment by a1gemmel** [comment]
The google maps API does call `window.gm_authFailure` if it's defined when authentication fails. It does not fire if the key is missing, however.

My initial concept of doing `load(resolveFn, rejectFn)` won't work, since as @krasimir mentioned the google api script loads _and then_ attempts to authenticate.

I think a another good approach here would be to add a method like `GoogleApiLoader.onAuthFail(callback)`, which would be triggered by `window.gm_authFailure`.

All events registered by `onLoad` and the callback passed to `load` would still fire, but at least there wouldn't be a 5 second latency before assuming process success.

**Comment by krasimir** [comment]
Or maybe the library returns a promise that is rejected with an error that has a `type`. Like:
```js
var GoogleMapsLoader = require('google-maps');

GoogleMapsLoader.load().then(
  function(google) {
    new google.maps.Map(el, options);
  },
  function(error) {
    switch(error.type) {
       case GoogleMapsLoader.ERROR_TIMEOUT: ...
       case GoogleMapsLoader.ERROR_AUTH: ...
    }
  });
```

**Comment by davidkudera** [comment]
Please, look at issue #38 where we discussed promise support.

Also keep in mind that there can be many `load()` calls (before or after google library is loaded).

**Comment by krasimir** [comment]
@davidkudera makes sense. I see why the API looks like that.

**Comment by davidkudera** [comment]
Hi and sorry for the long human-timeout. Please check out the new version 4.1.1. It's now written in typescript and supports await/async.

It also automatically captures two kinds of errors - load error and authentication errors.

with await/async:

```typescript
try {
  await loader.load();
catch (e) {
  console.log(e);
}
```

or without it:

```javascript
loader.load().catch((e) => console.log(e));
```
