### ISSUE TITLE
Allow instances of GoogleMapsLoader

### ISSUE THREAD

**Issue by Swiftwork** [davidkudera/google-maps-loader#44]
If I inject GoogleMapsLoader into an Angular2 component as googleMapsLoader and then assign the KEY value before running load it will be ignored, due to the fact that GoogleMapsLoader in not looking for [**"this"** value but rather the **static**ally defined version](https://github.com/Carrooi/Js-GoogleMapsLoader/blob/develop/lib/Google.js#L102).

```typescript
import { GoogleMapsLoader } from 'google-maps';
import { MapConfig } from './map-config';

@Injectable()
export class GoogleMapsService {

  private googleMaps: any;

  constructor(
    private googleMapsLoader: GoogleMapsLoader
  ) {
    this.googleMapsLoader.KEY = MapConfig.GOOGLE_MAPS_API_KEY;
    this.googleMapsLoader.LIBRARIES = MapConfig.GOOGLE_MAPS_LIBRARIES;
    this.googleMapsLoader.load((google: any) => {
        this.googleMaps = google.maps;
        const map = new this.googleMaps.Map(mapView.nativeElement, {
          styles: MapConfig.GOOGLE_MAPS_STYLE,
        });
      });
   }
 }
```

**Comment by davidkudera** [comment]
Hi, the reason why this package is static is, that you basically can't have more instancies of google maps object in one time.

I have similar service (or wrapper) in our app, but it just uses the static `GoogleMapsLoader` inside.

**Comment by Swiftwork** [comment]
I would have thought it be better to have the loader instantiable but the Google Maps reference static (window object value) and refer to it if the Google already exists.

**Comment by davidkudera** [comment]
Hi, please, check out the new version 4.1.1. It's now written in typescript and supports await/async.

Also, there is now a `Loader` class which you must instantiate. Angular example:

```typescript
import {NgModule} from '@angular/core';
import {Loader} from 'google-maps';

@NgModule({
    providers: [
        {
            provide: Loader,
            useFactory: () => {
                return new Loader('my-api-key');
            },
        },
    ],
})
export class AppModule {}
```
