### ISSUE TITLE
Is there a way to serve a local version of the maps.js

### ISSUE THREAD

**Issue by leggomuhgreggo** [davidkudera/google-maps-loader#48]
Can't leverage browser caching with the cdn version, and I get a point reduction on [google page speed insights](https://developers.google.com/speed/pagespeed/insights/). So I was wondering if there was some way to serve it locally.

Thanks!

**Comment by davidkudera** [comment]
Hello, sorry, there is no option for that, this library is only an async loader for the official google maps js api. It uses `<script async>` attribute and can be used anywhere in your code. So my suggestion is to just load it later when needed.

Also please check out the new version 4.1.1. It's written in typescript and supports await/async
