### ISSUE TITLE
Not compatible with ES2015 modules

### ISSUE THREAD

**Issue by nertzy** [davidkudera/google-maps-loader#54]
If you try to load this library as an ES2015 module into TypeScript, you cannot set the variables such as CLIENT, CHANNEL, etc.

Maybe we should add setter functions for each of these variables. Or accept an optional options object when calling load().

**Comment by davidkudera** [comment]
Hello, like it is said in the docs, this library is commonjs compatible. 

There were already many requests for this and so I [plan](https://github.com/Carrooi/Js-GoogleMapsLoader/issues/52) to rewrite whole library to es6 module.

**Comment by davidkudera** [comment]
Hello and sorry for the long human-timeout. Please check out the new version 4.1.1. It's now written in typescript and supports await/async.
