### ISSUE TITLE
No satellite option, zoom in/out options in Google Maps IOS Device

### ISSUE THREAD

**Issue by saiprasad2595** [davidkudera/google-maps-loader#59]
Hi,
I am not able to see satellite , zoom in /out buttons on the google map in IOS device.Attached a screenshot for reference.
After inspecting the device i found that display none is present for class 'gmnoprint'. 
Also for full screen button i cant see any image loaded in the dom.Same in the case of zoom in/out.
But in the browser and android device i am not getting this issue.Can anyone suggest how to fix this?
![screen shot 2018-02-16 at 1 45 37 pm](https://user-images.githubusercontent.com/8768464/36299064-4340dd4e-1321-11e8-8e9a-1330d6016a0a.png)
![image-1](https://user-images.githubusercontent.com/8768464/36299084-68c8cd9c-1321-11e8-8da8-1f1dad2f4e8e.jpg)

Thanks,
Best Wishes,
Saiprasad.

**Comment by davidkudera** [comment]
Hi, please check out the new version 4.1.1. It's written in typescript and supports await/async.

Your problem seems to be with the actual google maps api and not with this package, which is just a loader. Stackoverflow would be more helpful. :wink:
