### ISSUE TITLE
error of styles in controls

### ISSUE THREAD

**Issue by NanoDev777** [davidkudera/google-maps-loader#60]
I have this strange problem, I do not know if it has happened to someone else .. when using Street View the controls of this one, they have some design problems ... (as shown in the image) neither the icons of rotation appear ... I think it's due to my configurations or if ?, Maybe to the version I'm using ?, Any comment is helpful, thanks
![img](https://user-images.githubusercontent.com/28969280/36575831-783b4be0-1823-11e8-84cc-9710ee1eab21.png)

**Comment by davidkudera** [comment]
Hello, please check out the new version 4.1.1. It's now written in typescript and supports await/async.

To answer you - it seems as a problem not related to this package which is only a loader for the official google maps js api. Stackoverflow would be more helpfull for such errors.
