### ISSUE TITLE
Unable to load API after initially being offline

### ISSUE THREAD

**Issue by zxc23** [davidkudera/google-maps-loader#63]
(Using this in an Electron app)

If I attempt to load the API while offline, I get an error like this:
`net::ERR_INTERNET_DISCONNECTED`

After reconnecting, I'm still unable to load the API.

**Comment by davidkudera** [comment]
Hello, if you're still interested in this, try the new version 4.1.1. It's written in typescript and supports await/async.

Feel free to reopen this issue if this problem persist.

**Comment by zxc23** [comment]
Thanks, will do.
