### ISSUE TITLE
__google_maps_api_provider_initializator__ callback not being called?

### ISSUE THREAD

**Issue by 814k31** [davidkudera/google-maps-loader#70]
Hey, I'm unfortunately struggling to get the api to work...
Environment: `react-js`
```js
import GoogleMapsLoader from 'google-maps';

GoogleMapsLoader.KEY = GOOGLE_MAPS_KEY;
GoogleMapsLoader.LIBRARIES = ['geometry', 'drawing', 'places', 'encoding'];

GoogleMapsLoader.load((google) => (
    // This is never called
    console.log('load callback')
));
```

I added some logs within the library itself and all looks good but I couldn't see that the callback is actually working
```js
window[GoogleMapsLoader.WINDOW_CALLBACK_NAME] = function() {
    console.log('google-maps library callback');
    ready(fn);
};
```
Do you have any tips?

**Comment by davidkudera** [comment]
Hello, please check out the new version 4.1.1. It's written in typescript and supports await/async.

The new version should be imported like this in typescript:

```typescript
import {Loader} from 'google-maps';
```

or without typescript:

```javascript
const {Loader} = require('google-maps');
```
