### ISSUE TITLE
Please update api version from 3.31 to 3.34

### ISSUE THREAD

**Issue by j574144** [davidkudera/google-maps-loader#71]
See mor info here.

https://developers.google.com/maps/documentation/javascript/error-messages#retired-version

Thanks.

**Comment by alexbaulch** [comment]
To expand on this issue, I can see that you have done the upgrade to 3.3.4 in this repo but the version on NPM is still using 3.3.1, so I think it's just a case of pushing the changes to NPM also.

**Comment by ALPIXELMaiki** [comment]
Please npm publish your repo to update the number version on npm :)

**Comment by NasH5169** [comment]
Waiting for the npm update and if you really have to target 3.34 google maps version, you can explicitly ask GoogleMapsLoader to load this version:

`GoogleMapsLoader.VERSION = '3.34'`

**Comment by TheBearSO** [comment]
@NasH5169 you are right, until the base version will be changed, you can override the version like this way.

**Comment by valentinoPereira** [comment]
> Waiting for the npm update and if you really have to target 3.34 google maps version, you can explicitly ask GoogleMapsLoader to load this version:
> 
> `GoogleMapsLoader.VERSION = '3.34'`

Thanks dude.. It worked on my Angular 5 project.

**Comment by TheBearSO** [comment]
@davidkudera could you publish the repo on npm as @alexbaulch and @ALPIXELMaiki said. This will really help to everybody.

**Comment by donmccurdy** [comment]
Perhaps the default should be `GoogleMapsLoader.VERSION = 'weekly';`, so that it doesn't need to be updated on a regular basis? That's the default when loading Maps API through a script: https://developers.google.com/maps/documentation/javascript/versions

**Comment by davidkudera** [comment]
Hello, please check out the new version 4.1.1 (written in typescript with await/async).

The version key is now not automatically prefilled, but can still be used if you want to:

```typescript
const loader = new Loader('my-api-key', {
    version: 'weekly',
});
```
