### ISSUE TITLE
Google Maps JavaScript API warning: RetiredVersion

### ISSUE THREAD

**Issue by justin-dunham** [davidkudera/google-maps-loader#73]
Console displays: Google Maps JavaScript API warning: RetiredVersion

The current release version 3.3.0 has an outdated version of the Google Maps API. It pulls in 3.31. This code change has already been made (Thanks @CAJ2) but there has not been an npm publish since this was merged.

PR with fix:
https://github.com/Carrooi/Js-GoogleMapsLoader/pull/68

**Comment by TheBearSO** [comment]
Check this https://github.com/Carrooi/Js-GoogleMapsLoader/issues/71#issuecomment-428914240, here you can override the version.

**Comment by donmccurdy** [comment]
Perhaps the default should be `GoogleMapsLoader.VERSION = 'weekly';`, so that it doesn't need to be updated on a regular basis? That's the default when loading Maps API through a script: https://developers.google.com/maps/documentation/javascript/versions

**Comment by davidkudera** [comment]
Hello, please check out the new version 4.1.1 (written in typescript with await/async).

The version key is now not automatically prefilled, but can still be used if you want to:

```typescript
const loader = new Loader('my-api-key', {
    version: 'weekly',
});
```
