### ISSUE TITLE
ERROR Error: Uncaught (in promise): TypeError: this.setValues is not a function

### ISSUE THREAD

**Issue by anushkaSinhaProctur** [davidkudera/google-maps-loader#74]
I am getting this error when i am adding multiple markers in my google map.

**Comment by anushkaSinhaProctur** [comment]
getMarkers() {
   // var marker;
     var locations = [
      ['Event 1', -25.344, 131.036,1],
      ['Event 2', -37.852086, 504.985963,2],
      ['Event 3', -35.299085, 509.109615,3],
      ['Event 4', -28.013044, 513.425586,4],
      ['Event 5', -31.951994, 475.858081,5]
    ]; 
   console.log(google.maps);
    for (var i = 0; i < locations.length; i++) {  
      var  marker =  google.maps.Marker({
        title: locations[i][0],
       position:  google.maps.LatLng(locations[i][1], locations[i][2]),
       animation:GoogleMapsAnimation.DROP 
        });
    
    }
     marker.showInfoWindow();

     
 
  };

 getMarkers() {
   // var marker;
     var locations = [
      ['Event 1', -25.344, 131.036,1],
      ['Event 2', -37.852086, 504.985963,2],
      ['Event 3', -35.299085, 509.109615,3],
      ['Event 4', -28.013044, 513.425586,4],
      ['Event 5', -31.951994, 475.858081,5]
    ]; 
   console.log(google.maps);
    for (var i = 0; i < locations.length; i++) {  
      var  marker =  google.maps.Marker({
        title: locations[i][0],
       position:  google.maps.LatLng(locations[i][1], locations[i][2]),
       animation:GoogleMapsAnimation.DROP 
        });
    
    }
     marker.showInfoWindow();

     
 
  }; getMarkers() {
   // var marker;
     var locations = [
      ['Event 1', -25.344, 131.036,1],
      ['Event 2', -37.852086, 504.985963,2],
      ['Event 3', -35.299085, 509.109615,3],
      ['Event 4', -28.013044, 513.425586,4],
      ['Event 5', -31.951994, 475.858081,5]
    ]; 
   console.log(google.maps);
    for (var i = 0; i < locations.length; i++) {  
      var  marker =  google.maps.Marker({
        title: locations[i][0],
       position:  google.maps.LatLng(locations[i][1], locations[i][2]),
       animation:GoogleMapsAnimation.DROP 
        });
    
    }
     marker.showInfoWindow();

     
 
  }; getMarkers() {
   // var marker;
     var locations = [
      ['Event 1', -25.344, 131.036,1],
      ['Event 2', -37.852086, 504.985963,2],
      ['Event 3', -35.299085, 509.109615,3],
      ['Event 4', -28.013044, 513.425586,4],
      ['Event 5', -31.951994, 475.858081,5]
    ]; 
   console.log(google.maps);
    for (var i = 0; i < locations.length; i++) {  
      var  marker =  google.maps.Marker({
        title: locations[i][0],
       position:  google.maps.LatLng(locations[i][1], locations[i][2]),
       animation:GoogleMapsAnimation.DROP 
        });
    
    }
     marker.showInfoWindow();

     
 
  }; getMarkers() {
   // var marker;
     var locations = [
      ['Event 1', -25.344, 131.036,1],
      ['Event 2', -37.852086, 504.985963,2],
      ['Event 3', -35.299085, 509.109615,3],
      ['Event 4', -28.013044, 513.425586,4],
      ['Event 5', -31.951994, 475.858081,5]
    ]; 
   console.log(google.maps);
    for (var i = 0; i < locations.length; i++) {  
      var  marker =  google.maps.Marker({
        title: locations[i][0],
       position:  google.maps.LatLng(locations[i][1], locations[i][2]),
       animation:GoogleMapsAnimation.DROP 
        });
    
    }
     marker.showInfoWindow();

     
 
  }; getMarkers() {
   // var marker;
     var locations = [
      ['Event 1', -25.344, 131.036,1],
      ['Event 2', -37.852086, 504.985963,2],
      ['Event 3', -35.299085, 509.109615,3],
      ['Event 4', -28.013044, 513.425586,4],
      ['Event 5', -31.951994, 475.858081,5]
    ]; 
   console.log(google.maps);
    for (var i = 0; i < locations.length; i++) {  
      var  marker =  google.maps.Marker({
        title: locations[i][0],
       position:  google.maps.LatLng(locations[i][1], locations[i][2]),
       animation:GoogleMapsAnimation.DROP 
        });
    
    }
     marker.showInfoWindow();

     
 
  }; getMarkers() {
   // var marker;
     var locations = [
      ['Event 1', -25.344, 131.036,1],
      ['Event 2', -37.852086, 504.985963,2],
      ['Event 3', -35.299085, 509.109615,3],
      ['Event 4', -28.013044, 513.425586,4],
      ['Event 5', -31.951994, 475.858081,5]
    ]; 
   console.log(google.maps);
    for (var i = 0; i < locations.length; i++) {  
      var  marker =  google.maps.Marker({
        title: locations[i][0],
       position:  google.maps.LatLng(locations[i][1], locations[i][2]),
       animation:GoogleMapsAnimation.DROP 
        });
    
    }
     marker.showInfoWindow();

     
 
  };
If I am adding new keyword before google.maps.Marker, then the error is as cannot read property 'maps' of undefined.

**Comment by davidkudera** [comment]
Hi, this seems like an issue with the original google maps js api and not an issue with this library (which is just a loader).

If you still have this problem, please try to ask on stackoverflow instead.

Also check out the new version of this library written in typescript with await/async support :wink:
