### ISSUE TITLE
How to access the map object after load?

### ISSUE THREAD

**Issue by sheepwall** [davidkudera/google-maps-loader#76]
Hello, it seems to be only me having this problem so I have misunderstood the usage of this package, also I am a JavaScript beginner.

I use the example code in the README and it loads alright. The problem is that I want to access the created "new google.maps.Map" object for manipulating the map in the rest of my code. How do I achieve this?

Thanks

**Comment by maxpaynestory** [comment]
Google maps is an asynchronous library. You need to provide code to google maps that it will run after it has finished loading.

**Comment by davidkudera** [comment]
Hi @sheepwall, if you're still interested, please check out the new version 4.1.1.

To answer your question, you can call the `.load()` function many times, but the API will be loaded only once:

```typescript
await Promise.all([
    loader.load(),
    loader.load(),
    loader.load(),
    loader.load(),
    loader.load(),
]);

await loader.load();
```

Even if you try to load it like in the example above (5 times in parallel and then once again) it will still be downloaded only once.
