### ISSUE TITLE
You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.

### ISSUE THREAD

**Issue by kimanihuon** [davidkudera/google-maps-loader#79]
Hi, am running on VUEJS and getting the above error. My application has multiple pages and this happens when a user navigates back to the maps page after navigating to a different page. 

Snippet:

_// Lazy loaded when a user opens the "maps" page_

import { Loader } from "google-maps";

    const loader = new Loader("[My API KEY]);

    const google = await loader.load();

    var location = { lat: -34.397, lng: 150.644 };

    // eslint-disable-next-line no-unused-vars
    const map = new google.maps.Map(document.getElementById("map"), {
      center: { lat: -34.397, lng: 150.644 },
      zoom: 8
    });

    // Add marker function to make it easy to add multiple locations
    function addMarker(props) {
      // eslint-disable-next-line no-unused-vars
      const mapMarker = new google.maps.Marker({
        position: props.coords,
        map: map,
        icon: props.image,
        title: props.title
      });

      // Pop up window
      const mapInfoWindow = new google.maps.InfoWindow({
        content: props.content
      });

      mapMarker.addListener("click", function() {
        mapInfoWindow.open(map, mapMarker);
      });
    }

    var img = require("@/assets/location.png");
    var content = "Sacrifices";

    // Repeat for multiple locations ** Use array and loop though
    addMarker({
      coords: location,
      image: img,
      title: "Queen Sac",
      content: "<h2>" + content + "<h2/>"
    });

**Comment by asonni** [comment]
I am facing this issue as well

**Comment by hongjisung** [comment]
i solve this using singleton pattern with loader

**Comment by kimanihuon** [comment]
> i solve this using singleton pattern with loader

Yes this works for me, find below my final version:

`
// Google maps loader
import { Loader } from "google-maps";

// Initializing with API key
const loader = new Loader("<API_KEY>");

export default { 

  async mounted() {
    const google = await loader.load();

    var location = { lat: -34.397, lng: 150.644 };

    // eslint-disable-next-line no-unused-vars
    const map = new google.maps.Map(document.getElementById("map"), {
      center: { lat: -138.397, lng: 150.644 },
      zoom: 8
    });

    // Add marker function to make it easy to add multiple locations
    function addMarker(props) {
      // eslint-disable-next-line no-unused-vars
      const mapMarker = new google.maps.Marker({
        position: props.coords,
        map: map,
        icon: props.image,
        title: props.title
      });

      // Pop up window
      const mapInfoWindow = new google.maps.InfoWindow({
        content: props.content
      });

      mapMarker.addListener("click", function() {
        mapInfoWindow.open(map, mapMarker);
      });
    }

    var img = require("@/assets/location.png");
    var content = "Sacrifices";

    // Repeat for multiple locations ** Use array and loop though
    addMarker({
      coords: location,
      image: img,
      title: "Queen Sac",
      content: "<h2>" + content + "<h2/>"
    });
  },
};


`

**Comment by pam1168** [comment]
> i solve this using singleton pattern with loader

Based on this idea, it works for me
```

const mySingleton = {};

// Define a static property that will be cached
mySingleton.cachedProperty = null;
mySingleton.googleMapApi = null;

// Define a function to fetch the data for the cached property
mySingleton.fetchData = async function(apiKey) {
 mySingleton.cachedProperty = 'Cached data';

  // Simulating an asynchronous data fetch
  const google =  await GoogleMapsApiLoader({
    apiKey: apiKey
  });

  mySingleton.googleMapApi = google

  return google
};

export default mySingleton;
```

You just need to check if mySingleton.cachedProperty has value or not to decide for loading google map

```
    if (!mySingleton.cachedProperty) {
      googleMapApi = await mySingleton.fetchData(this.apiKey)

      this.google = googleMapApi;
      this.initializeMap();
    } else {...}
```

Hope this simple code could help someone. :)
