### ISSUE TITLE
No longer possible to use without bundler?

### ISSUE THREAD

**Issue by simonbengtsson** [davidkudera/google-maps-loader#83]
Recent versions only works with bundler? Before with the Google.js file things were exported to the global scope? Now when using index.js in a script tag on a page it gives an error of undefined variables `exports`.

**Comment by davidkudera** [comment]
That is correct, version 4.0.0 was a complete rewrite.

**Comment by simonbengtsson** [comment]
Is there a reason for this or would you accept a PR exporting in umd format again?

**Comment by davidkudera** [comment]
Newer versions are "pure" typescript implementations, which don't play so nicely with UMD. I simply don't want to clutter the code with multiple different exports when everyone and everything is slowly moving to `import/export` (with bundlers for now) anyway.

But I'm thinking about supporting [pika.dev](https://www.pika.dev/). You can maybe check out their Snowpack bundler which seems really lightweight and simple.

**Comment by simonbengtsson** [comment]
Sounds like a reasonable approach. It seems native esm modules with pure javascript does not work either however. When using this simple example it gives the `Uncaught ReferenceError: exports is not defined` error.

```
<script type="module">
import { Loader } from './google-maps/lib/index.js'
</script>
```

**Comment by davidkudera** [comment]
Thank you for trying. I'll try to update it soon, your comment made me curious how difficult it will be :wink:

**Comment by davidkudera** [comment]
So, we have a new tag `4.3.1`. There are now 2 compiled versions - CommonJS and ESM. There should be no change for the previous usage.

@simonbengtsson can you please try to include `google-maps/lib/esm/index.js`?

I'm also waiting for pika to update. It should be possible to use ESM version of this package directly from their CDN.

**Comment by davidkudera** [comment]
Pika seems to be working too:

```html
<script type="module">
  import { Loader } from 'https://cdn.pika.dev/google-maps';
  console.log(Loader);
</script>
```

**Comment by simonbengtsson** [comment]
Sweet! Seems to work out well 👌
