### ISSUE TITLE
getAnchor method not found in google-maps.js

### ISSUE THREAD

**Issue by chuckdawit** [davidkudera/google-maps-loader#85]
I'm using this npm and it works fine for creating the map and setting markers, but as soon as I try and add an info window the library throws an error because it's looking for a method that doesn't exist!

The method - getAnchor() // line 1122 in google-maps.js

Here is the method in full - 

open(anchor) {
       this._assertInitialized();
       this._elementRef.nativeElement.style.display = '';
       this.infoWindow.open(this._googleMap.googleMap, anchor ? anchor.getAnchor() : undefined);
}

I stepped through it to make sure the 'anchor' being passed in has values and is instantiated, there just isn't a getAnchor method.

Did I not do something correctly to pass in the 'MapMarker' to this call?
FYI - 'MapMarker' is from "@angular/google-maps"

Here is a SO link I posted about this problem.
https://stackoverflow.com/questions/62845428/google-map-npm-angular-package-throwing-error-when-opening-info-window-getancho#62851940

**Comment by davidkudera** [comment]
Hi, there is an accepted answer on SO. I presume that you solved this problem, so I'm closing this issue now.

**Comment by chuckdawit** [comment]
Hi.
Thank you.
The tutorial I was looking at had some bad code.
Chuck
