### ISSUE TITLE
Ionic Capacitor

### ISSUE THREAD

**Issue by niojihy** [davidkudera/google-maps-loader#87]
const loader = new Loader(apiKey, options);

"There is no application set to open the URL capacitor://maps.googleapis.com/maps/api/js?...."

Change :

return `//maps.googleapis.com/maps/api/js?${parameters.join('&')}`;

To:

return `https://maps.googleapis.com/maps/api/js?${parameters.join('&')}`;

**Comment by seanaye** [comment]
@niojihy can confirm this fixes the issue in a capacitor app. I made a fork if you want to use it in the meantime `yarn remove google-maps && yarn add google-maps-cap`

**Comment by medfx** [comment]
Url is loading fine in Android WebView Capacitor, but iOS UIWebView is not loading. You need to use @niojihy fork, or switch to @googlemaps/js-api-loader.

**Comment by davidkudera** [comment]
Thanks, fixed in version 4.3.3
