### ISSUE TITLE
Package should be depricated

### ISSUE THREAD

**Issue by thesilican** [davidkudera/google-maps-loader#88]
Google recently added it's own [official google maps loader](https://www.npmjs.com/package/@googlemaps/js-api-loader). They even mentioned this project in their README.

I highly encourage you to deprecate this project and/or add a notice in the README that points to the official google maps loader.

**Comment by davidkudera** [comment]
Thanks for letting me know about this. I don't plan to deprecate this package (for now), but I updated the readme.
