### ISSUE TITLE
Support: IE11

### ISSUE THREAD

**Issue by zangab** [davidkudera/google-maps-loader#92]
I am using this package in combination with webpack as an es6 module via import.
In the changelog, there's an entry v4.2.3 together with the message "Add support for IE11".
However, I can NOT confirm that. As soon as I add the code for the map, the js runs into a syntax error, in IE11.

You are using async-await / Promises which are NOT supported in IE by default, so what does this "Add support for IE11" actually mean?

**Comment by xtools-at** [comment]
4.2.3 seems to work fine on IE11. However, I recently updated to 4.3.3 but it broke entirely unfortunately, so project's back to 4.2.3

**Comment by zangab** [comment]
nvm, dropped the library anyway...
